# Premiers pas

A chaque etape, vous devez soumettre en appuyant sur "Run cell" (flèche) ou en utilisant le raccourci clavier (Shift+Entree)

In [1]:
from pylab import *

In [2]:
print "Hello world!"

Hello world!


La fonction print affiche

In [4]:
x = 5
y = 6
z = 6.


In [5]:
x/y 
x/z

0.8333333333333334

In [6]:
print x/y 
print x/z

0
0.833333333333


In [7]:
sin(2 *pi)

-2.4492935982947064e-16

In [8]:
exp(2 * 1j * pi)

(1-2.4492935982947064e-16j)

Le premier nombre est très proche de zero, le deuxième est un nombre complexe très proche de 1. A noter que 1j en Python désigne le nombre complexe i tel que i2=−1.

## Les booléens

In [23]:
type(True)
print True and False
print False or True
print True and not False

False
True
True


## Chaînes de caractères

In [24]:
nom = "Elève"
age = 23
phrase = "Je m'appelle " + nom + " j'ai " + str(age) + " ans."
print phrase
 

Je m'appelle Elève j'ai 23 ans.


## Import de fonction, librairies

Il y a un très grand nombre de librairires python, et ces librairies contiennent beaucoup de fonctions. Pour pouvoir utiliser une fonction ou une classe dans une librairie, il est nécessaire de l'importer dans chaque script avant de s'en servir, et par convention on le fait en début de script. Il y a plusieurs manières d'importer des Fonctions (ou classes). Dans l'exemple qui suit, nous chargeons et utilisons la fonction randn qui permet de simuler une matrice avec des entrées gaussiennes i.i.d. Nous le faisons de cinq façons différentes, mais la fonction randn importée est à chaque fois exactement la même.

In [26]:
# Methode 1
from numpy.random import randn
X = randn(3, 3)

# Methode 2
import numpy
X = numpy.random.randn(3, 3)

# Methode 3 : on cree un alias de numpy.random que l'on appelle npr
import numpy.random as npr
X = npr.randn(3, 3)

# Methode 4 : on importe toute les fonction de numpy.random
from numpy.random import *
X = randn(3, 3)

# Methode 5 : on importe les fonctions les plus utilisees de numpy, scipy, matplotlib
from pylab import *
X = randn(3, 3)

# Pour importer plusieurs fonction d'une meme librairie
from numpy import ones, zeros, empty

L'import de pylab utilisé dans la cinquième méthode permet d'importer de façon concise toutes les fonctions les plus courantes des librairies numpy, scipy et matplotlib. C'est cette méthode que nous utiliserons dans les TP.

Tous vos scripts commenceront donc par

In [27]:
from pylab import *

Il y aura quelques cas exceptionnels, ou nous aurons besoin, dans un même script, de deux fonctions qui portent le même nom mais qui sont différentes. Dans l'exemple suivant, nous utilisons deux fonctions s'appelant toutes les deux poisson. La première fonction est dans numpy.random et permet de simuler des variables de loi de Poisson, alors que la deuxième est dans scipy.stats et permet d'obtenir la valeur de la densité de probabilité de la loi de Poisson.

In [6]:
from pylab import *
import numpy.random as npr
import scipy.stats as sps

mu = 0.5
n = 1000
m = 2
X = npr.poisson(mu, n)  # Simulation de variables de loi de Poisson d'intensite mu
x = arange(m+1) # x contient un vecteur numpy d'entiers [0, 1, 2, ... , m]
f = sps.poisson.pmf(x, mu) # Densite de probabilite de la loi de Poisson d'intensite mu aux points x

In [7]:
X

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2,
       2, 0, 0, 2, 1, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 3, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 2, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 2, 1, 1, 2, 0, 1, 1, 1, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 2, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 2, 1, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 2, 1, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       2, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0,

In [34]:
x

array([0, 1, 2])

In [35]:
f

array([ 0.60653066,  0.30326533,  0.07581633])

## Objets de base en Python

### List

In [36]:
a = [66.25, 333, 333, 1, 1234.5]                 # Attention:la numero de position a partir de zero
print a.count(333), a.count(66.25), a.count('x') # compte le nombre d'occurences d'un objet
# affiche 2 1 0
a.insert(2, -1)                                  # insere -1 en deuxieme position
a.append(333)                                    # ajouter 333 en derniere position
print a
# affiche [66.25, 333, -1, 333, 1, 1234.5, 333]
a.index(333)                                     # donne la position d'un element
# affiche 1
a.remove(333)                                    # enleve la premiere occurence d'un objet
print a
# affiche [66.25, -1, 333, 1, 1234.5, 333]
a.reverse()                                      # renverse la liste
print a
# affiche [333, 1234.5, 1, 333, -1, 66.25]
a.sort()                                         # trie la liste
print a
# affiche [-1, 1, 66.25, 333, 333, 1234.5]

2 1 0
[66.25, 333, -1, 333, 1, 1234.5, 333]
[66.25, -1, 333, 1, 1234.5, 333]
[333, 1234.5, 1, 333, -1, 66.25]
[-1, 1, 66.25, 333, 333, 1234.5]


Une list est un object qui contient une liste d'objets, sous forme d'un tableau. Elle peut contenir n'importe quel type d'objets. Attention cependant, pour le calcul numérique vectoriel et matriciel, on préférera toujours utiliser des tableaux numpy (voir plus bas), pour faire des calculs plus rapides.

### Tuple

In [37]:
t = 12345, 54321, "Bonjour!"
print t[0]
# affiche 12345
print t
# affiche (12345, 54321, 'hello!')
u = t, (1, 2, 3, 4, 5) # On peut emboiter des tuples
print u
# affiche ((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))
# On ne peut pas modifier un tuple (on dit qu'il est immutable)
t[0] = 88888
# affiche: Traceback (most recent call last):
#            File "<stdin>", line 1, in <module>
#            TypeError: 'tuple' object does not support item assignment

12345
(12345, 54321, 'Bonjour!')
((12345, 54321, 'Bonjour!'), (1, 2, 3, 4, 5))


TypeError: 'tuple' object does not support item assignment

Le tuple ressemble beaucoup a une list, mais une fois crée on ne peut pas changer ses éléments. Cet objet sert par exemple à représenter la dimension d'une matrice dans la librarie numpy (voir plus bas). On peut notamment se servir d'un tuple comme clé dans un dict

### Dict

In [1]:
tel = {'agathe': 4098, 'bertrand': 4139}
tel['eleve'] = 4127
print tel
print tel['eleve']
del tel['bertrand']
print tel
print tel.keys()
print tel.values()
print "bertrand" in tel 

{'agathe': 4098, 'bertrand': 4139, 'eleve': 4127}
4127
{'agathe': 4098, 'eleve': 4127}
['agathe', 'eleve']
[4098, 4127]
False


Le dict est une table de hashage, qui permet d'associer des clés à des valeurs. Les valeurs peuvent être de type quelconque, les clés peuvent être de type int, float, string (chaîne de caractère), tuple, ou pour être plus précis, tout type “hashable”.

### Set

In [ ]:
basket = ['pomme', 'orange', 'pomme', 'poire', 'orange', 'banane']
fruit = set(basket)   # Le set qui contient ces fruits (donc sans repetitions)
print fruit
# affiche set(['orange', poire', 'apple', 'banana'])
print 'orange' in fruit                  # est ce que orange est dans fruit ?
# affiche True
print 'kiwi' in fruit
# affiche False
a = set('abracadabra')                   # L'ensemble des lettres contenues dans abracadabra
b = set('alacazam')
print a
# affiche set(['a', 'r', 'b', 'c', 'd'])
print a - b                              # lettres dans a mais pas dans b
# affiche set(['r', 'd', 'b'])
print a | b                              # lettres dans a ou dans b
# affiche set(['a', 'c', 'r', 'd', 'b', 'm', 'z', 'l'])
print a & b                              # dans a et b
# affiche set(['a', 'c'])
print a ^ b                              # lettres dans a ou b mais pas dans les deux
# affiche set(['r', 'd', 'b', 'm', 'z', 'l'])

Le set est un ensemble au sens mathématique, il contient un objet une seule fois. Il peut contenir n'importe quel type d'objet. On peut faire des opérations ensemblistes comme décrit au dessus.

## Quelques remarques

Nous listons ici quelques remarques fondamentales sur python, qui vont vous éviter de faire les erreurs les plus habituelles, et vous faire gagner du temps.

### Les objects en python ne sont pas copiés

In [3]:
x = [4, 2, 10, 9, "toto"]
y = x  # y est juste une reference au tableau x, pas de copie effectuee ici
y[2] = "tintin"
print x # Cela affiche  [4, 2, "tintin", 9, "toto"]
x = [4, 2, 10, 9, "toto"]
y = x[:]   # On demande une copie
y[2] = "tintin"
print x # Cela affiche  [4, 2, 10, 9, "toto"]

[4, 2, 'tintin', 9, 'toto']
[4, 2, 10, 9, 'toto']


### L'indexation des tableaux commence a zéro

In [4]:
x = [4, 3, 12]
print x[1] # affiche 3

3


### La division est entière (dans python2.*)

In [5]:
print 1 / 2 # affiche 0
print 1. / 2 # affiche 0.5
print 1 / .2 # affiche 0.5

0
0.5
5.0


### L’échange de deux variables a et b se fait en une ligne

In [6]:
a, b = b, a

NameError: name 'b' is not defined

### L’élevation à la puissance

In [7]:
print 1000 ** (3 / 2)    # affiche 1000 (3/2 = 1)
print 1000 ** (3 / 2.)   # affiche 31622.7766017

1000
31622.7766017


x ** y élève x a la puissance y. Encore une fois, attention à la division entière

### La fonction range

In [ ]:
x = range(5)
print x # affiche [0, 1, 2, 3, 4]
x = range(-10, -100, -30)
print x # affiche [-10, -40, -70]

La fonction range renvoie une list python contenant une suite arithmétique. On verra plus bas la fonction arange de numpy, qui fait la même chose, mais qui construit un array numpy.

# Definitions de fonctions

## L'indentation est fondamentale en python

In [9]:
def fib(n):               # dans la fonction fib
    a, b = 0, 1
    while a < n:
        print a,          # dans la boucle while
        a, b = b, a+b
fib(100)                  # en dehors de la fonction fib

0 1 1 2 3 5 8 13 21 34 55 89


Tout le contenu de la fonction fib est indenté d'une tabulation. Tout le contenu de la boucle while est également indenté d'une tabulation (donc deux en tout). La ligne fib(10) est en dehors de la définition de la fonction fib, donc n'est pas indenté. A noter que la virgule dans print a, evite le retour à la ligne lors de l'affichage.

### Déclaration d'une fonction

In [ ]:
def f(tata, toto=2, tintin=4):
    print tata, toto, tintin
f(3)  # affiche 3 2 4
f(3, 5, 12)  # affiche 3 5 12
f(3, tintin=5, toto=12)  # affiche 3 12 5
f(tintin=5, toto=12, tata=123)  # affiche 123 12 5 

La déclaration d'une fonction python se fait avec le mot-clé def. On doit déclarer en premier les paramètres sans valeurs par défaut, puis ceux avec une valeur par défaut. Les paramètres avec une valeur par défaut sont nommés. On peut se servir du nom des paramètres dans l'appel à la fonction

### Une fonction est un objet comme un autre

In [10]:
f = fib  # f est le meme objet que fib
f(100)

0 1 1 2 3 5 8 13 21 34 55 89


## Structures de contrôle et boucles

### Le if elif else

In [11]:
x = int(raw_input("Donne moi un entier: "))
if x < 0:          # est-ce que x est negatif ?
    x = 0          # si oui on le remplace par zero
    print "Je remplace ton nombre negatif par zero"
elif x == 0:       # est-ce que x est egal a zero ?
    print 'Zero'   # si oui on affiche "Zero"
elif x == 1:       # est-ce que x est egal a 1 ?
    print 'Un'     # si oui on affiche "Un"
else:              # sinon
    print 'Plus'   # on affiche "Plus"

Donne moi un entier: 2
Plus


### La boucle for (premier exemple)

In [12]:
for i in range(11):
  # commandes

IndentationError: expected an indented block (<ipython-input-12-827967d20b74>, line 2)

on fait varier un indice i entre 0 et 10 (compris)

### La boucle for (deuxième exemple)

In [13]:
for i in range(2, 8):
  # commandes

IndentationError: expected an indented block (<ipython-input-13-be84f0b13c42>, line 2)

### On peut itérer sur beaucoup d'objets

In [14]:
X = [10., [1, 2, 3], "Bonjour", 4]
for x in X:
    print x
# affiche successivement 10. puis [1, 2, 3] puis Bonjour puis 4

s = "Bonjour"
for c in s:
    print c
# affiche B o n j o u r

10.0
[1, 2, 3]
Bonjour
4
B
o
n
j
o
u
r


### Une fonction pratique: enumerate

In [15]:
X = [10., [1, 2, 3], "Bonjour", 4]
for i, x in enumerate(X):
  print i, x
# affiche :
# 0 10.0
# 1 [1, 2, 3]
# 2 Bonjour
# 3 4

0 10.0
1 [1, 2, 3]
2 Bonjour
3 4


permet d'itérer sur un object, en incrémentant automatiquement un compteur

### Itérer sur un dict

In [16]:
enseignants = { "prof1": "Michel", "prof2": "Guilloux"}
enseignants["prof5"] = "??"
for prof in enseignants: # itere sur les cles du dict
    print prof
for prof in sorted(enseignants): # itere sur les cles triees du dict
    print prof
for prof, nom in sorted(enseignants.items()): # itere sur les paires (cle, valeur) du dict, triees par cle
    print prof, nom


prof2
prof1
prof5
prof1
prof2
prof5
prof1 Michel
prof2 Guilloux
prof5 ??


On rappelle que enseignants.keys() donne les clés du dict et que enseignants.values() donne les valeurs du dict

### La boucle while

In [17]:
i = 1
while i < 100:
    print i
    i *= 3

1
3
9
27
81


### La liste comprehension

In [19]:
print [i ** 2 for i in range(20) if (3 * i) % 2 == 0]

[0, 4, 16, 36, 64, 100, 144, 196, 256, 324]


C'est une façon concise de créer des list python, en itérant sur des valeurs et avec éventuellement des conditions

## Remarque importante : le mot-clé pass

La syntaxe de python fait qu'on ne peut pas laisser une fonction ou une structure de contrôle vide. Il faut alors utiliser le mot-clé pass



### Mot-clé pass

In [20]:
def f(x):
    # Une super fonction que je coderai plus tard
    pass
for i in range(10):
    # Une boucle tres compliquee que je coderai plus tard
    pass

## Calcul matriciel, la librarie numpy  

### Un premier exemple

Donnons un premier exemple de calcul numérique avec numpy. Imaginons que l'on cherche une valeur approchée de la probabilité que le sinus d'une v.a. gaussienne standard soit ≤1/2. On peut procéder comme cela :

In [21]:
from pylab import *

n = 1000
X = randn(n)            # on genere n gaussiennes i.i.d standard
p = mean(sin(X) < 0.5)  # on applique la fonction sin a tous les elements de X, puis
                        #   on calcule le nombre moyen d'element < 0.5
print "Proba que sin(X) < 0.5 quand X est de loi N(0, 1)=", p

Proba que sin(X) < 0.5 quand X est de loi N(0, 1)= 0.702


### Quelques remarques de base sur numpy

#### Le premier élément d'un tableau numpy est d'indice 0

In [22]:
x = array([4, 1, 2])
print x[0] # affiche 4
 

4


#### python ne fait pas de copie, sauf si demandé explicitement

In [23]:
y = x         # y est le meme object que x (si on modifie x on modifie y et inversement)
y = x.copy()  # y est une copie de x
y = x[:]      # si x et y sont de meme taille on remplit le contenu de x dans y
y[:] = x      # idem

Comme dit avant, python ne fait pas de copie sauf si cela est demandé explicitement. C'est donc aussi le cas pour les tableaux numpy.



#### arange  

In [24]:
from pylab import *
x = arange(5)
print x


[0 1 2 3 4]


arange donne le tableau numpy d'entiers suivant une suite arithmétique. NB: range() renvoie une list python alors que arange() renvoie un tableau numpy



#### valeurs dans un tableau numpy

In [25]:
from pylab import *
n = 4
x = arange(n) # x contient [0, 1, 2, 3]
y = x / 4     # y contient [0, 0, 0, 0], car c'est une division entiere
y = x / 4.    # y contient [ 0. 0.25 0.5 0.75]
x = array(x, dtype=double)
y = x / 4     # y contient [ 0. 0.25 0.5 0.75]

Dans un tableau numpy, les valeurs sont typées (par exemple int, float, double, complex, etc.) et sont forément de même type (ce qui n'est pas le cas d'une list python). La plupart des fonctions de numpy ont un argument optionnel appelé dtype. Par exemple zeros((2, 3), dtype=int) donne une matrice de taille 2×3 à valeurs int (entières), alors que zeros((2, 3), dtype=double) donne une matrice à valeurs réelles (double précision). Le type de valeurs dans un tableau numpy peut être très important, comme dans l'exemple ci-dessus.

Quelques remarques en vrac

Si x est un tableau numpy alors x.shape donne sa dimension
ones((3, 4)) donne une matrice de taille 3×4 qui ne contient que des 1 (par defaut de type double)
zeros((3, 4)) donne une matrice de taille 3×4 qui ne contient que des 0 (par defaut de type double)
eye(4) donne la matrice identité de taille 4×4 (par defaut de type double)
ones(X.shape) donne une matrice de même taille que X qui ne contient que des 1
X. est la matrice transposee de X
Les opérations +, -, *, /, **, +=, *=, /=, -=, etc. sont programmées de façon à être appliquées terme à terme aux tableaux numpy. Par exemple, si A et B sont des matrices de même taille, alors A * B calcule la matrice qui contient les produits terme à terme (produit Hadamard) des matrices A et B. Pour calculer le produit matriciel entre A et B on utilise dot(A, B).
La plupart des fonctions mathématiques classiques sont programmées de façon matricielle. Si X est une matrice (ou vecteur) numpy, alors exp(X), sin(X), etc. correspondent aux applications des fonctions exp, sin, etc. à chaque entrée de X. De même, pour x un scalaire, X + x correspond à l'addition de x terme à terme dans X.

#### booléens et test dans un tableau numpy

In [26]:
from pylab import *
x = array([4, 2, 1, 5, 1, 10])
logical_and(x >= 3, x <= 9, x != 1)  # vaut [ True False False True False False]

array([ True, False, False,  True, False, False], dtype=bool)

Pour X matrice et a un scalaire, X <= a est la matrice de même taille que X où les entrées sont remplacées par des booléens True (=vrai) et False (=faux) selon qu'elles soient ou non ≤a. Cela se généralise à des opérations à valeurs booléennes plus compliquées (encadrements, etc.) et permet souvent d’éviter le recours à des boucles et/ou des tests.




Les fonctions logical_and, logical_or, logical_not, logical_xor sont disponibles pour appliquer les opérations logiques et, ou, non, xor termes à termes entre tableaux numpy


#### Générateurs de nombres aléatoires


Il y a de nombreux générateurs de nombres aléatoires dans numpy.random : randn génère des gaussiennes et rand des lois uniformes sur [0,1]. Toutes les lois classiques sont disponibles, cf : http://docs.scipy.org/doc/numpy/reference/routines.random.html

#### Construction d'une matrice par blocs

In [27]:
from pylab import *
A = array([[2, 1, 1], [4, 3, 0]])
B = array([[1, 2], [12, 0]])
C = array([[1, 2], [12, 0], [-1, 2]])
D = array([[1, 2, -4], [2, 0, 0], [1, 2, 3]])
print bmat([[A, B], [C, D]])

[[ 2  1  1  1  2]
 [ 4  3  0 12  0]
 [ 1  2  1  2 -4]
 [12  0  2  0  0]
 [-1  2  1  2  3]]


On peut construire une matrice par blocs, à partir de sous-matrices, en utilisant la fonction bmat.



#### Argument axis

Beaucoup de fonctions de numpy ont un argument nommé axis. Par exemple sum(X, axis=1) calcule la somme de chaque ligne de X, cumsum(X, axis=0) calcule la somme cumulée des colonnes de X, etc.

#### La lecture/écriture de tableaux numpy

In [28]:
X = randn(1000, 1000) # On genere une matrice gausienne standard iid
save("X.npy", X)      # On l'enregistre dans un fichier appele "X.npy"
X2 = load("X.npy")    # On charge le fichier "X.npy" dans un objet appele X2

La lecture/écriture de tableaux numpy se fait avec les fonctions load et save. L'enregistrement sur le disque est fait en format binaire, donc on ne peut pas visualiser ce type de fichier avec un éditeur de texte par exemple. La convention est de donner l'extension .npy à ce type de fichier

## Affichages graphique, la librairie matplotlib

Quelques fonctions de base pour faire des représentations graphiques avec matplotlib. On regardera la documentation de matplotlib pour plus de détails, cf :

http://matplotlib.org/api/pyplot_summary.html donne un résumé des fonctions principales

http://matplotlib.org/users/pyplot_tutorial.html est un bon tutoriel pour commencer

Et quelques “recettes de cuisine” matplotlib dont ici :http://matplotlib.org/users/recipes.html

http://matplotlib.org/gallery.html donne beaucoup d'exemples, avec le code source utilisé pour les obtenir


En résumé :

plot(x, y) affiche la courbe affine par morceaux reliant les points d'abscisses x et d'ordonnée y


hist(x) trace l'histogramme du vecteur x. Il faut spécifier l'option normed=True pour afficher l'histogramme normalisé (d'aire égale à 1)

bar(x, y, width=1.) , affiche un diagramme en bâtons aux positions x et hauteurs y label=“loi empirique”)

scatter(x, y) affiche le nuage de points d'abscisses x et d'ordonnée y

stem(x, y) affiche des barres verticales en position x et de hauteur y

show() affiche les fenêtres créées dans le script

figure() crée une nouvelle fenêtre graphique

title() permet de donner un titre à une figure

legend() affiche la légende d'un graphique

subplot() subdivise la fenêtre graphique de façon à y afficher plusieurs graphiques dans la même figure

#### Un exemple

In [ ]:
import numpy.random as npr
import scipy.stats as sps

# Intensite de la loi de Poisson
mu = 0.5
# Nombre de simulations
N = 1000
# Simulation de N variables de loi de Poisson d'intensite mu
X = npr.poisson(mu, N)
# count[k] contient la proportion de k dans le vecteur X
counts = bincount(X) / float(N)
# x contient 0, 1, , ..., M ou M est le maximum de X
x = arange(len(counts))
# f_x contient la probabilite theorique de la loi de Poisson en x
f_x = sps.poisson.pmf(x, mu)
# On affiche un bar plot pour la distribution empirique
bar(x - 0.5, counts, width=1., label="loi empirique")
# On affiche un stem plot pour la distribution theorique
p2 = stem(x, f_x, "r", label="loi theorique")
legend()
show()

Presque toutes les fonctions de matplotlib acceptent un argument optionel label, qui permet de donner un nom à au graphe tracé, et générer ainsi facilement une légende. Par exemple, le script suivant affiche une la distribution empirique d'un échantillon simulé de loi de poisson avec un bar plot, et affiche la distribution théorique avec un stem plot :

### Calcul scientifique, la librarie scipy

 la librairie scipy principalement pour obtenir facilement les densités, fonctions de répartition et fonctions quantiles des lois classiques. Cela est disponible dans scipy.stats. Un exemple avec la loi de poisson est donné au dessus.